food_mapping = {
        "🍕": "Pizza",
        "🍔": "Hamburger",
        "🍟": "French Fries",
        "🍣": "Sushi",
        "🍦": "Ice Cream",
        "🍓": "Strawberry",
        "🍝": "Spaghetti",
        "🍜": "Noodles",
        "🍛": "Curry Rice",
        "🍤": "Shrimp Tempura",
        "🍩": "Doughnut",
        "🍪": "Cookie",
        "🍰": "Cake",
        "🍫": "Chocolate Bar",
        "🍬": "Candy",
        "🍭": "Lollipop",
        "🍯": "Honey Pot",
        "🍍": "Pineapple",
        "🥑": "Avocado",
        "🥖": "Baguette Bread",
        "🧀": "Cheese Wedge",
        "🍇": "Grapes",
        "🍈": "Melon",
        "🍉": "Watermelon",
        "🍊": "Tangerine",
        "🍋": "Lemon",
        "🍌": "Banana",
        "🍎": "Red Apple",
        "🍏": "Green Apple",
        "🍐": "Pear",
        "🍑": "Peach",
        "🍒": "Cherries",
        "🥕": "Carrot",
        "🥦": "Broccoli",
        "🍄": "Mushroom",
        "🍅": "Tomato",
        "🥔": "Potato",
        "🥓": "Bacon",
        "🥞": "Pancakes",
        "🍽️": "Fork and Knife",
        "🥢": "Chopsticks",
        "🌮": "Taco",
        "🌯": "Burrito",
        "🍖": "Meat on Bone",
        "🥩": "Cut of Meat",
        "🍗": "Chicken Leg",
        "🍔": "Hamburger",
        "🍟": "French Fries",
        "🍕": "Pizza",
        "🍲": "Pot of Food",
        "🥗": "Green Salad",
        "🍜": "Steaming Bowl",
        "🍛": "Curry Rice",
        "🍝": "Spaghetti",
        "🍠": "Roasted Sweet Potato",
        "🍢": "Oden",
        "🍣": "Sushi",
        "🍤": "Fried Shrimp",
        "🍥": "Fish Cake with Swirl",
        "🍡": "Dango",
        "🍦": "Soft Ice Cream",
        "🍧": "Shaved Ice",
        "🍨": "Ice Cream",
        "🍩": "Doughnut",
        "🍪": "Cookie",
        "🎂": "Birthday Cake",
        "🍰": "Shortcake",
        "🧁": "Cupcake",
        "🥧": "Pie",
        "🍫": "Chocolate Bar",
        "🍬": "Candy",
        "🍭": "Lollipop",
        "🍯": "Honey Pot",
        "🍇": "Grapes",
        "🍈": "Melon",
        "🍉": "Watermelon",
        "🍊": "Tangerine",
        "🍋": "Lemon",
        "🍌": "Banana",
        "🍍": "Pineapple",
        "🍎": "Red Apple",
        "🍏": "Green Apple",
        "🍐": "Pear",
        "🍑": "Peach",
        "🍒": "Cherries",
        "🥭": "Mango",
        "🍅": "Tomato",
        "🍆": "Eggplant",
        "🥑": "Avocado",
        "🥒": "Cucumber",
        "🌽": "Ear of Corn",
        "🍄": "Mushroom",
        "🥜": "Peanuts",
        "🌰": "Chestnut",
        "🍞": "Bread",
        "🥐": "Croissant",
        "🥖": "Baguette Bread",
        "🥞": "Pancakes",
        "🧇": "Waffle",
        "🍟": "French Fries",
        "🍔": "Hamburger",
        "🍕": "Pizza",
        "🌭": "Hot Dog",
        "🥪": "Sandwich",
        "🍱": "Bento Box",
        "🍲": "Pot of Food",
        "🍛": "Curry Rice",
        "🍜": "Steaming Bowl",
        "🍝": "Spaghetti",
        "🍠": "Roasted Sweet Potato",
        "🍢": "Oden",
        "🍣": "Sushi",
        "🍤": "Fried Shrimp",
        "🍥": "Fish Cake with Swirl",
        "🥮": "Moon Cake",
        "🍡": "Dango",
        "🥟": "Dumpling",
        "🥠": "Fortune Cookie",
        "🥡": "Takeout Box",
        "🍦": "Soft Ice Cream",
        "🍧": "Shaved Ice",
        "🍨": "Ice Cream",
        "🍩": "Doughnut",
        "🍪": "Cookie",
        "🎂": "Birthday Cake",
        "🍰": "Shortcake",
        "🧁": "Cupcake",
        "🥧": "Pie",
        "🍫": "Chocolate Bar",
        "🍬": "Candy",
        "🍭": "Lollipop",
        "🍯": "Honey Pot",
        "🍇": "Grapes",
        "🍈": "Melon",
        "🍉": "Watermelon",
        "🍊": "Tangerine",
        "🍋": "Lemon",
        "🍌": "Banana",
        "🍍": "Pineapple",
        "🍎": "Red Apple",
        "🍏": "Green Apple",
        "🍐": "Pear",
        "🍑": "Peach",
        "🍒": "Cherries",
        "🥭": "Mango",
        "🍅": "Tomato",
        "🍆": "Eggplant",
        "🥑": "Avocado",
        "🥒": "Cucumber",
        "🌽": "Ear of Corn",
        "🍄": "Mushroom",
        "🥜": "Peanuts",
        "🌰": "Chestnut",
        "🍞": "Bread",
        "🥐": "Croissant",
        "🥖": "Baguette Bread",
        "🥨": "Pretzel",
        "🥯": "Bagel",
        "🥞": "Pancakes",
        "🧇": "Waffle",
        "🍟": "French Fries",
        "🍔": "Hamburger",
        "🍕": "Pizza",
        "🌭": "Hot Dog",
        "🥪": "Sandwich",
        "🍱": "Bento Box",
        "🍲": "Pot of Food",
        "🍛": "Curry Rice",
        "🍜": "Steaming Bowl",
        "🍝": "Spaghetti",
        "🍠": "Roasted Sweet Potato",
        "🍢": "Oden",
        "🍣": "Sushi",
        "🍤": "Fried Shrimp",
        "🍥": "Fish Cake with Swirl",
        "🥮": "Moon Cake",
        "🍡": "Dango",
        "🥟": "Dumpling",
        "🥠": "Fortune Cookie",
        "🥡": "Takeout Box",
        "🍦": "Soft Ice Cream",
        "🍧": "Shaved Ice",
        "🍨": "Ice Cream",
        "🍩": "Doughnut",
        "🍪": "Cookie",
        "🎂": "Birthday Cake",
        "🍰": "Shortcake",
        "🧁": "Cupcake",
        "🥧": "Pie",
        "🍫": "Chocolate Bar",
        "🍬": "Candy",
        "🍭": "Lollipop",
        "🍯": "Honey Pot",
        "🍇": "Grapes",
        "🍈": "Melon",
        "🍉": "Watermelon",
        "🍊": "Tangerine",
        "🍋": "Lemon",
        "🍌": "Banana",
        "🍍": "Pineapple",
        "🍎": "Red Apple",
        "🍏": "Green Apple",
        "🍐": "Pear",
        "🍑": "Peach",
        "🍒": "Cherries",
        "🥭": "Mango",
        "🍅": "Tomato",
        "🍆": "Eggplant",
        "🥑": "Avocado",
        "🥒": "Cucumber",
        "🌽": "Ear of Corn",
        "🍄": "Mushroom",
        "🥜": "Peanuts",
        "🌰": "Chestnut",
        "🍞": "Bread",
        "🥐": "Croissant",
        "🥖": "Baguette Bread",
        "🥨": "Pretzel",
        "🥯": "Bagel",
        "🥞": "Pancakes",
        "🧇": "Waffle",
        "🥮": "Moon Cake",
        "🥟": "Dumpling",
        "🥠": "Fortune Cookie",
        "🥡": "Takeout Box",
        "🍽️": "Fork and Knife",
        "🥢": "Chopsticks",
        "🍴": "Fork and Knife with Plate",
        "🥄": "Spoon",
        "🕴️": "Person in Suit Levitating",  # Just for fun!
        # Add more emoji-to-string mappings as needed
    }

ret = []
for emoji, des in food_mapping.items():
    ret.append(f"{str(emoji)} - {des}")
print(str(ret))

lst = [5, 7]
str_lst = str(lst)
print(str_lst)
